//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWebApplication.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.ICalculatorWcfService1")]
    public interface ICalculatorWcfService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorWcfService1/GetData", ReplyAction="http://tempuri.org/ICalculatorWcfService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorWcfService1/GetData", ReplyAction="http://tempuri.org/ICalculatorWcfService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorWcfService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ICalculatorWcfService1/GetDataUsingDataContractResponse")]
        WcfServiceCalculator.CompositeType GetDataUsingDataContract(WcfServiceCalculator.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorWcfService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ICalculatorWcfService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WcfServiceCalculator.CompositeType> GetDataUsingDataContractAsync(WcfServiceCalculator.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorWcfService1Channel : CalculatorWebApplication.ServiceReference2.ICalculatorWcfService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorWcfService1Client : System.ServiceModel.ClientBase<CalculatorWebApplication.ServiceReference2.ICalculatorWcfService1>, CalculatorWebApplication.ServiceReference2.ICalculatorWcfService1 {
        
        public CalculatorWcfService1Client() {
        }
        
        public CalculatorWcfService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorWcfService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWcfService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWcfService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WcfServiceCalculator.CompositeType GetDataUsingDataContract(WcfServiceCalculator.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WcfServiceCalculator.CompositeType> GetDataUsingDataContractAsync(WcfServiceCalculator.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
